Ongoing backup operations
knoxite/knoxite pull request #154
Opened 2020-09-04 17:41 UTC by penguwin

This pr brings support for ongoing backup operations in knoxite. When using the 'ongoing' option knoxite will still pursue the current backup operation and prints out a list of the erroneous files with errormessage.

 You can set 'ongoing' via the `-o | --ongoing` command line flag or, per repo, in the configuration file.

This also should fix #54

2020-09-04 18:41 UTC, ma-hartma approved these changes
Great contribution! Looks good to me.

2020-09-17 00:59 UTC, muesli requested changes
Almost there!

2020-09-17 00:59 UTC, muesli commented on cmd/knoxite/restore.go
> +			stats.Errors += 1
`stats.Errors++` would suffice.

2020-09-17 00:59 UTC, muesli commented on cmd/knoxite/store.go
> +	f().BoolVar(&opts.Pedantic, "pedantic", false, "continue on failue")
Typo in `failue`.

2020-09-17 00:59 UTC, muesli commented on cmd/knoxite/store.go
> +				snapshot.Stats.Errors += 1
`snapshot.Stats.Errors++` would suffice.

2020-09-17 00:59 UTC, muesli commented on cmd/knoxite/store.go
> +					return p.Error
`fmt.Println()` removed accidentally.

2020-09-17 01:12 UTC, ma-hartma approved these changes

2020-09-17 01:19 UTC, muesli approved these changes
Fantastic, I think we can merge this!

2020-09-17 01:20 UTC, merged