Introduce --loglevel flag and logging interface
knoxite/knoxite pull request #203
Opened 2021-09-20 20:55 UTC by ma-hartma

This PR introduces a --loglevel flag to let the user set the level of verbose output to Fatal, Warn, Info or Debug.
The -v flag will only set the log level to "Info".
There is also a new "Print" log level to replace fmt for normal output, a logger interface and a NopLogger for quiet output if no logger has been set for the knoxite library.

There already is a PR to update the website: [Website PR 69](https://github.com/knoxite/website/pull/69)

2021-09-20 21:18 UTC, ma-hartma commented
Tests were only not successful because of a coveralls.io maintenance.

2021-11-03 18:36 UTC, penguwin approved these changes
LGTM!

2021-11-03 18:36 UTC, penguwin commented on cmd/knoxite/main.go
> +	RootCmd.PersistentFlags().BoolVarP(&globalOpts.Verbose, "verbose", "v", false, "Verbose output on log level Info. Use --loglevel to choose between Debug, Info, Warning and Fatal")
Would probably be nice to have an increasing verbosity level from here using cobras `CountVarP()`. So using the `-v` flag results in loglevel `Info` and using `-vv` turns it into loglevel `Debug`.

2021-11-03 19:22 UTC, penguwin requested changes

2021-11-03 19:23 UTC, ma-hartma commented on cmd/knoxite/main.go
> +	}
thanks!

2021-11-03 19:27 UTC, penguwin approved these changes

2021-11-26 21:31 UTC, merged